# Arrays
https://numpy.org/doc/stable/reference/routines.array-creation.html

In [1]:
import numpy as np

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

### np.arange(posi, posn, step)

In [3]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Arrays
* np.zeros(size) or np.zeros((column, row))
* np.ones(size) or np.ones((column, row))
* np.linspace(valueIn, valueEnd, cant)
* np.eye(size) **Create a matriz with main diagonal in 1**
* np.random.rand() **Create random number between 0 and 1
* np.random.rand(size) **Create vector of size value with random numbers between 0 and 1
* np.random.rand(size, size) **Create matriz of size value with random numbers between 0 and 1
* np.random.randint(betwen values) **Between initial and final value
* np.random.randint(betwen values, (structure)) **Between initial and final value in a structure for example matriz x * x

In [14]:
print('vector->', np.zeros(5))
print('matriz \n', np.zeros((5,3)))

vector-> [0. 0. 0. 0. 0.]
matriz 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
print('vector->', np.ones(5))
print('matriz \n', np.ones((5,3)))

vector-> [1. 1. 1. 1. 1.]
matriz 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
print('number->', np.random.rand())
print('vector->', np.random.rand(4))
print('matriz \n', np.random.rand(3,4))

number-> 0.2545451332647458
vector-> [0.46643351 0.47042564 0.0315963  0.83310091]
matriz 
 [[0.54743057 0.94846987 0.2783     0.02160377]
 [0.48674369 0.25698393 0.45079389 0.80553324]
 [0.1973641  0.45077276 0.60641066 0.42615505]]


In [17]:
print('single: ', np.random.randint(1,15))
print('matriz: \n', np.random.randint(1,15,(10,10)))

single:  7
matriz: 
 [[ 6  9  6 13 14  5  7  4 10  9]
 [ 3 12  7 13 11  7  6  5  7  4]
 [12  2  8  3  2  7  7 10  7 13]
 [14 13  1  5  5 12  4  2  8  2]
 [12  6  5  2 11 11 12 13  5 13]
 [11 14  4  7  7 11 11 12  7  3]
 [ 7  3 11 11 10  1  4  6  4 12]
 [ 6  3  9 13 14  1  4 13 14  7]
 [ 7  5  1 12  9  6  9 10  6 10]
 [ 8  3 13 10  3  5 13  4 14  6]]
