# Shape y reshape
https://numpy.org/doc/stable/reference/generated/numpy.ndarray.shape.html

In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1,10,(3,2))

In [4]:
arr.shape

(3, 2)

In [14]:
print('Original \n', arr)
print('form 1. ->',arr.reshape(1,6))
print('form 2. ->',np.reshape(arr,(1,6)))
print('Form C \n', np.reshape(arr,(2,3),'C')) # Language C
print('Form F \n', np.reshape(arr,(2,3),'F')) # Language Fortran
print('Form A \n', np.reshape(arr,(2,3),'A')) # Memory save optimization

Original 
 [[2 4]
 [3 2]
 [9 6]]
form 1. -> [[2 4 3 2 9 6]]
form 2. -> [[2 4 3 2 9 6]]
Form C 
 [[2 4 3]
 [2 9 6]]
Form F 
 [[2 9 2]
 [3 4 6]]
Form A 
 [[2 4 3]
 [2 9 6]]
