# Main functions in Numpy
## Statistics
https://numpy.org/doc/stable/reference/routines.statistics.html
## Mathematical
https://numpy.org/doc/stable/reference/routines.math.html


In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,20,10)
arr

array([12, 17,  7, 13, 14,  4, 14, 15, 18, 13])

In [4]:
matriz = arr.reshape(2,5)
matriz

array([[12, 17,  7, 13, 14],
       [ 4, 14, 15, 18, 13]])

In [5]:
arr.max()

18

In [6]:
print('max total->', matriz.max())
print('max for dimension->', matriz.max(1))

max total-> 18
max for dimension-> [17 18]


In [7]:
print('indice of max value->', arr.argmax())

indice of max value-> 8


In [8]:
print('indice of max value->', matriz.argmax())
print('indice for dimension->', matriz.argmax(0))
print('indice for dimension->', matriz.argmax(1))

indice of max value-> 8
indice for dimension-> [0 0 1 1 0]
indice for dimension-> [1 3]


In [11]:
print('min vector->', arr.min())
print('min matriz total->', matriz.min())
print('min matriz for dimension->', matriz.min(1))

min vector-> 4
min matriz total-> 4
min matriz for dimension-> [7 4]


In [12]:
print('indice of min value->', matriz.argmin())
print('indice for dimension->', matriz.argmin(0))
print('indice for dimension->', matriz.argmin(1))

indice of min value-> 5
indice for dimension-> [1 1 0 0 1]
indice for dimension-> [2 0]


In [14]:
# Peak to peak
print('Min value->', arr.min())
print('Max value->', arr.max())
print('Peak to peak', arr.ptp())

Min value-> 4
Max value-> 18
Peak to peak 14


In [19]:
# Percentile: In this case midle value of the array
print(arr)
print('Percentile 0->', np.percentile(arr, 0))
print('Percentile 50->', np.percentile(arr, 50))    # Median
print('Percentile 100->', np.percentile(arr, 100))

[12 17  7 13 14  4 14 15 18 13]
Percentile 0-> 4.0
Percentile 50-> 13.5
Percentile 100-> 18.0


In [21]:
# Median & sort
arr.sort()
print(arr)
print('Percentile 50->', np.percentile(arr, 50))    # Median
print('Median->', np.median(arr))

[ 4  7 12 13 13 14 14 15 17 18]
Percentile 50-> 13.5
Median-> 13.5


In [22]:
# Standard deviation
arr.std()

4.050925820105819

In [23]:
# Variance
arr.var()

16.41

In [24]:
# Mean
arr.mean()

12.7

## Concat arrays of diferents dimensions

In [31]:
# Concat
m1 = np.array([[1,2],[3,4]])
m2 = np.array([5,6])

In [32]:
np.concatenate((m1,m2), axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [33]:
print(f'M1: {m1.ndim}, M2: {m2.ndim}')

M1: 2, M2: 1


In [34]:
m2 = np.expand_dims(m2, axis=0)
m2.ndim

2

In [35]:
np.concatenate((m1,m2), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

### Transposed ( T )

In [39]:
np.concatenate((m1,m2), axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [38]:
m2.T

array([[5],
       [6]])

In [40]:
np.concatenate((m1,m2.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])