# Copy
https://numpy.org/doc/stable/reference/generated/numpy.copy.html

In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
part = arr[0:6]
part

array([0, 1, 2, 3, 4, 5])

In [4]:
part[:] = 0
print('Part array->',part)
print('Original array->',arr)

Part array-> [0 0 0 0 0 0]
Original array-> [ 0  0  0  0  0  0  6  7  8  9 10]


In [5]:
origin = np.arange(0, 11)
origin

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
copy = origin.copy()
copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
copy[:] = 30
print('Origin->',origin)
print('Copy->',copy)

Origin-> [ 0  1  2  3  4  5  6  7  8  9 10]
Copy-> [30 30 30 30 30 30 30 30 30 30 30]
