# Operations
https://numpy.org/doc/stable/user/absolute_beginners.html#basic-array-operations

In [1]:
import numpy as np

In [2]:
list = [1,2]
list * 2 # Wrong

[1, 2, 1, 2]

In [3]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr2 = arr.copy()

# Multiplication
arr2 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
# Adition
arr2 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
# divide
1 / arr2

/tmp/ipykernel_1107/3297143446.py:2: RuntimeWarning: divide by zero encountered in divide
  1 / arr2


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [11]:
# Exp
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [12]:
# Adition of arrays
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
matriz = arr.reshape(2,5)
matriz1 = matriz.copy()
matriz1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
# Product point in arrays
np.matmul(matriz, matriz1.T)

array([[ 30,  80],
       [ 80, 255]])

In [17]:
matriz @ matriz1.T

array([[ 30,  80],
       [ 80, 255]])